stages:
  - build
  - package

maven-build:
  stage: build
  image: maven:3.8-openjdk-17
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour

docker-build:
  stage: package
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t spring-demo:latest .
    - echo "Docker image built successfully"
  dependencies:
    - maven-build